GET http://127.0.0.1:8000/member/member/count
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2ODkxMzIzMDQsIm1vYmlsZSI6IjEzMDAwMDAwMDAxIiwiaWQiOjE2Nzg5Njg2NjgyMDMxMjY3ODQsImV4cCI6MTY4OTE2ODMwNCwiaWF0IjoxNjg5MTMyMzA0fQ.wsiWtMFVoLMU0X_n7J0HfVE1g-JMFvA1nUhSIw9_KBc

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=1234

###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "13000000001"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13000000001",
  "code": "8888"
}

###