POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test5",
  "idCard": "123459",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1678976605260746752,
  "name": "test0",
  "idCard": "123455",
  "type": "1"
}

###

GET http://localhost:8000/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###

DELETE http://localhost:8000/member/passenger/delete/1678976605260746752
Accept: application/json
token: {{token}}
